project:
  type: website

website:
  title: "bite-sized-workshops"
  navbar:
    left: 
      - text: "R Series"
        menu: 
        - text: "Episode 1"
          href: Episode1.html
      - text: "Now You See It!"
        href: introTableau.html
      - text: "Introduction QGIS"
        href: introQGIS.html
      - text: "Google"
        href: https://google.com        
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

